export const AVENIR_NEXT="Avenir Next"
export const AVENIR_NEXT_BOLD ="AvenirNext-Bold"
export const AVENIR_NEXT_DEMI_BOLD="AvenirNext-DemiBold"
export const AVENIR_NEXT_DEMI_MEDIUM="AvenirNext-Medium"
export const AVENIR_NEXT_DEMI_REGULAR="AvenirNext-Regular"